### ISSUE TITLE
ES6 Formatting

### ISSUE THREAD

**Issue by jeffshek** [geezhawk/django-react-auth#11]
Willing to entertain if I rewrite some parts of this to ES6 in a PR?

Generic Things:

- Specifically switching var to let/cosnt
- New function annotation 

- Changing import patterns to 
>  import { name1, name2 } from 'src/my_lib';
>  import localName from 'src/my_lib';

This will require babel / webpack to translate though - so that's the tradeoff ...

**Comment by coxjonc** [comment]
Go for it!

**Comment by yarnball** [comment]
@jeffshek Did you end up changing this over to ES6? Im intersted, or could help out

**Comment by jeffshek** [comment]
Ported over to a personal open project, but didn't really ever get around to coming back to this =/

I was originally learning ES6 at the time and didn't realize how bad I was at writing Javascript so it ended up being too consuming. 

To do it right for this project, a lot of the stuff should be reflected, all in the last year - ie. React just went through a few major changes, Router 4 had a lot of breaking changes, etc. Webpack has to be brought up to v2. 

It honestly should be done though. This is by far one of the best guides on django/react/auth out there on the web.
